// REPOSITORIES CONSTANTS

export const DATA_SOURCE = 'DATA_SOURCE';

export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const ORDER_ITEM_REPOSITORY = 'ORDER_ITEM_REPOSITORY';

// catalogue
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';

// cart
export const CART_REPOSITORY = 'CART_REPOSITORY';
export const CART_ITEM_REPOSITORY = 'CART_ITEM_REPOSITORY';
